FORMAT: 1A
HOST: https://my-card.in/

# MyCard API
MyCard API is a service about yu-gi-oh, YGOPro and MyCard.

MyCard API is in BETA now, means unstable and changeable. If you are developing with it, please contact zh99998<zh99998@gmail.com>.

# Group Decks
Decks related resources of the **MyCard API**
All User-related API need a *HTTP Basic* Auth.

## Decks Collection [/decks/{user}.json]
+ Parameters
    + user (required, string, `zh99998`) ... String `user` of the Deck belongs to.

### Get all Decks of a user[GET]
+ Response 200 (application/json)

        [
            {
                id: "52ad12d5a913b1e378da31cb"
                name: "Exodia",
                user: {
                    id: "52663da78c51ebaf06000001"
                   name: "zh99998",
                   points: 102,
                },
                created_at: "2013-12-15T02:24:21+00:00",
                updated_at: "2013-12-15T02:24:21+00:00",
                deleted: false,
                card_usages: [
                    {
                        card_id: 33396948,
                        side: false,
                        count: 1
                    },
                    {
                        card_id: 7902349,
                        side: false,
                        count: 1
                    },
                    {
                        card_id: 8124921,
                        side: false,
                        count: 1
                    },
                    {
                        card_id: 44519536,
                        side: false,
                        count: 1
                    },
                    {
                        card_id: 70903634,
                        side: false,
                        count: 1
                    }
                ],
                version: 1,
            }
        ]

## Deck [/decks/{user}/{name}.json]
A single Deck object with all its details

+ Parameters
    + user (required, string, `zh99998`) ... String `user` of the Deck belongs to.
    + name (required, string, `Exodia`) ... String `name` of the Deck.

### Retrieve a Deck [GET]
+ Response 200 (application/json)

        {
            id: "52ad12d5a913b1e378da31cb"
            name: "Exodia",
            user: {
                id: "52663da78c51ebaf06000001"
               name: "zh99998",
               points: 102,
            },
            created_at: "2013-12-15T02:24:21+00:00",
            updated_at: "2013-12-15T02:24:21+00:00",
            deleted: false,
            card_usages: [
                {
                    card_id: 33396948,
                    side: false,
                    count: 1
                },
                {
                    card_id: 7902349,
                    side: false,
                    count: 1
                },
                {
                    card_id: 8124921,
                    side: false,
                    count: 1
                },
                {
                    card_id: 44519536,
                    side: false,
                    count: 1
                },
                {
                    card_id: 70903634,
                    side: false,
                    count: 1
                }
            ],
            version: 1,
        }


### Create or update a Deck [PUT]
+ Request (application/x-www-form-urlencoded)

        updated_at=2013-08-20T21:41:08-07:00&cards=J_ZjUIeJSNIe_n5Kp1BwMOedS

+ Request (application/json)

        will support if you need it and contact zh99998<zh99998@gmail.com>

+ Response 201
    + Headers

            Location: https://my-card.in/decks/zh99998/sample.json

+ Response 204

+ Response 409

### Remove a Deck [DELETE]
+ Response 204

+ Response 410