<?php
	define('KEY', "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_=");
	header("Content-type: application/x-ygopro-deck");
	header('Content-Disposition: attachment; filename*=utf-8\'\''.rawurlencode($_REQUEST['name'].'.ydk')); 
	$cards_encoded = $_REQUEST['cards'];
	$result_main = array();
	$result_side = array();
    for($i=0; $i < strlen($cards_encoded); $i += 5){
    	$decoded = 0;
    	foreach(str_split(substr($cards_encoded, $i, 5)) as $char){
    		$decoded = ($decoded << 6) + strpos(KEY, $char);
    	}
    	$card_id = $decoded & 0x07FFFFFF;
    	$side = $decoded >> 29;
      	$count = $decoded >> 27 & 0x3;
    	for($j=0; $j<$count; $j++){
    		if($side){
    			$result_side[]=$card_id;
    		}else{
    			$result_main[]=$card_id;
    		}
    	}
    }
    echo(join("\r\n", array_merge(array("#generated by mycard"), $result_main, array("!side"), $result_side)));
?>
